Ed-Fi-Alliance-OSS/ed-fi-alliance-oss.github.io

docs/intro/index.md

I have added some update recommendations in the text.

MY_Update index.md

---

blog/2024-05-28.md
blog/2024-05-31.md
blog/2024-06-26.md
blog/2024-07-11.md
blog/2024-08-12.md
blog/2024-09-20.md
blog/authors.yml
package-lock.json
package.json

I did not create a ticket in the documentation or other projects. I just don't see it as necessary for blogging. There is no need to create a traceability path back to a ticket with requirements for a blog - at least, not as a general requirement. For a specific case it could be useful, like linking to a release ticket.

Blog updates Sept 26, 2024

---

odsApi_versioned_docs/version-7.3/getting-started/source-code-installation/project-templates-installation.md

https://dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_artifacts/feed/EdFi/NuGet/EdFi.Suite3.ProjectTemplates.Installer/overview/7.3.10

[ODS-6561] EdFi.Suite3.ProjectTemplates.Installer 7.3 version updated

---

package-lock.json
package.json

Bump Dependabot 112024

---

docs/partners/2-certification/certificationData.js

Skyward SMS 2.0 fix

---

docs/reference/4-metaed/ide-user-guide/common-problems-and-troubleshooting.md
docs/reference/4-metaed/ide-user-guide/core-concepts.md
docs/reference/4-metaed/ide-user-guide/correcting-language-warnings-and-errors.md
docs/reference/4-metaed/ide-user-guide/creating-and-maintaining-your-extension.md
docs/reference/4-metaed/ide-user-guide/upgrading-to-metaed-4x.md
docs/reference/4-metaed/ide-user-guide/using-the-generated-artifacts.md
docs/reference/4-metaed/language-specification/reserved-words.md
docs/reference/4-metaed/releases/4.2.1.md
docs/reference/4-metaed/releases/4.3.0.md
docs/reference/4-metaed/releases/4.4.0.md
docs/reference/4-metaed/releases/4.5.0.md

Screenshots from the release page are below. The image is hidden in an expandable section because it is relatively large and people might not look past it for more information.

[METAED-1581] MetaEd 4.5 Release

---

docusaurus.config.js
package-lock.json
package.json

Updates package vulnerabilities
Adds config to docusaurus to support "Edit this page" functionality.

[Bump] Package versions. Docusaurus config update.

---

dataStandard_versioned_docs/version-5/readme.md
dataStandard_versioned_docs/version-5/whats-new/readme.md
dataStandard_versioned_docs/version-5/whats-new/whats-new-v52.md

- Links on the Ed-Fi Data Standard page is updated to reflect the new release DS v5.2
- What's New - v5.2 link is added to the What's New Overview page
- What's New - v5.2 sub-page is added with details of the DS model updates from v5.1 to v5.2

[DOC-159] DS v5.2 Release Updates

---

dataStandard_versioned_docs/version-5/handbook.md
dataStandard_versioned_docs/version-5/model-reference/readme.md

- Unifying Data Model Handbook p[age is updated to have v5.2 info and link instead of v5.1
- Unifying Data Model - v5 Model Reference page is updated with the DS v5.2 Handbook and UML diagram links

[DOC-160] Handbook and UML updates

---

docs/partners/1-badging/badgeData.js

Added Xello to badge registry

---

dataStandard_versioned_docs/version-5/model-reference/student-attendance-domain/best-practices-and-use-cases/readme.md

This ticket is to fix the issue occurred when Student Attendance Domain Best Practices page was transferred from Confluence to Ed-Fi Docs website.

[DOC-158] Fix the with the Student Attendance Domain Best Practices

---

docusaurus.config.js
package-lock.json
package.json

Adds a dismissable announcement banner that redirects users to the "Latest Releases" blog page.
Starting with the built-in configuration and evaluating effectiveness / feedback before pursuing custom banner component.
Also upgrades React from 18 to 19.

[DOC-183] Add announcment banner

---

docs/reference/6-data-import/readme.md

Adding note about Earthmover / Lightbeam

Adding note about Earthmover / Lightbeam to Data Import page

---

docs/partners/2-certification/certificationData.js

Add Amplify to assessment registry

Add Amplify Assessment Certification information

---

docs/partners/2-certification/available-certifications/assessment-v4/certification-steps.md

Adds changes to the original DOC-182 PR
https://github.com/Ed-Fi-Alliance-OSS/ed-fi-alliance-oss.github.io/pull/186

[DOC-182] PR Changes

---

blog/2025-02-28.md
blog/authors.yml

- Summary of 2024 State Extension Analyses
- With links to Data Standard best practices documents
- With links to each state specific analysis report and aggregated report

[DOC-191] 2024 State Extension Analysis Blog Post

---

docs/partners/2-certification/available-certifications/sis-v4/test-scenarios/readme.md
docs/partners/2-certification/available-certifications/sis-v5/test-scenarios/readme.md
odsApi_versioned_docs/version-7.2/client-developers-guide/resource-dependency-order.md
odsApi_versioned_docs/version-7.3/client-developers-guide/resource-dependency-order.md
package-lock.json
package.json

Updates the diagram for Resource Dependency Order in the ODS/API Client Developers Guide. This is for 7.3 and 7.2

[DOC-193] Update resource dep order for ods-api 7.3 and 7.2

---

blog/2025-03-13.md
blog/2025-03-17.md
package-lock.json

And update to milestone 0.4.0 release announcement

Call for DMS posters at Tech Congress

---

docs/partners/1-badging/badgeData.js
docs/partners/2-certification/available-certifications/assessment-v4/certification-steps.md
docs/partners/2-certification/available-certifications/domain-api-v4/certification-steps.md
docs/partners/2-certification/certificationData.js

registry entry, removed Istation and K12 Analytics, fixed availablity statement

Added Authentica to MSP registry, updated Focus

---

src/pages/reference.jsx

Me, to Copilot:
> I am a web site developer who needs to create a landing page that describes the Ed-Fi technology suite, with links to detailed documentation about: Ed-Fi technology roadmap, Ed-Fi Data Standard, Ed-Fi ODS/API, Ed-Fi Data Management Service, Ed-Fi Admin API, Ed-Fi API Publisher, and MetaEd. Please draft the text for this page.
Required a little editing, but not much. Of course I added the extra links at the end, since my prompt didn't include those. 
I also asked:
> What images should I include?
I don't have time right now to act on it (even with Copilot's help), but here are its suggestions, which are generally interesting:
---
Including relevant and visually appealing images can greatly enhance your landing page. Here are some suggestions for images to include:
Hero …

Improved reference page

---

docs/reference/1-data-exchange/udm/getting-started/core-concepts.md

Cross-link to help people find the handbooks

---

docs/partners/1-badging/badgeData.js

EA Starting Blocks and Podium product registry updated

EA Starting Blocks and Podium product registry

---

blog/2025-05-23.md

blog post for Admin Console 1 RC1

blog post for Admin Console 1 RC1

---

docs/getting-started/educator-pipeline/use-cases/sea-playbook-data-utilization.md
docs/reference/10-educator-pipeline/1-clinical-experience/other-related-resources.md
docs/reference/10-educator-pipeline/1-clinical-experience/use-case.md
docs/reference/10-educator-pipeline/2-program-diversity/other-related-resource.md
docs/reference/10-educator-pipeline/2-program-diversity/use-case.md
src/pages/reference.jsx

Adds ther SEA Playbook Advancing Data Utilization to Support Educator Preparation and Teacher Workforce

Adds EPP SEA Playbook data-utilization to docs

---

docs/getting-started/edfi-exchange/technology/learning-standards-sync/getting-started.md

Some download links were missing.

Learning standards downloads

---

DEVELOPER.md
docs/reference/6-data-import/getting-started/installation/powershell-installation-for-data-import-using-nuget-packages.md
docs/reference/6-data-import/technical-articles/hotfixes/di-1270.md
docs/reference/6-data-import/technical-articles/preprocessing-csv-files/integrated-custom-file-processors.md
docs/reference/6-data-import/technical-articles/readme.md
package-lock.json
package.json

This pull request introduces several updates to documentation and tooling, focusing on improving clarity, adding new commands, and enhancing style consistency. Key changes include the addition of a new `npm` command for folder-specific linting, updates to documentation for better readability, and replacing placeholder image descriptions with meaningful alt text.
* Added a new `npm run lint:folder` command in `package.json` to allow folder-specific linting of Markdown and MDX files. (`[package.jsonR17](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R17)`)
* Updated `DEVELOPER.md` to document the usage of the new `npm run lint:folder` command, including an example of its usage. (`[DEVELOPER.mdR31](diffhunk://#diff-35ea617bfbf0780bfbc554348314c5b11ba478a4d98f …

[DI-1404] Add linting command for specific folder and update Markdown in Data Import

---

dataStandard_versioned_docs/version-5/model-reference/discipline-domain/best-practices.md

Fixed some typos and added a note regarding that if an incident involves a student from another school then an incident should be created for each school.

DATASTD-1256 Updated Best Practices Documentation

---

blog/2025-07-29-admin-app-api-publisher-release-summary.md
blog/authors.yml
docusaurus.config.js

Adds the API Pub 1.3.0 and Admin App 3.3.4 releases to the Ed-Fi documentation as a blog.

[AA-1782] API Pub 1.3 and Admin App 3.3.4 Release Blog

---

docs/getting-started/educator-pipeline/use-cases/sea-playbook-data-utilization.md

Updates the Playbook to include a link to the Webinar Advancing Educator Preparation Through State-Level Data Innovation.

Add video webinar to SEA Playbook advancing data utilization.

---

docs/getting-started/educator-pipeline/use-cases/sea-playbook-data-utilization.md

Update to Educator Pipeline [Data Utilization Use Case](https://docs.ed-fi.org/getting-started/educator-pipeline/use-cases/sea-playbook-data-utilization/)

Add tweak to SEA Playbook Spotlight description.

---

docs/reference/3-admin-api/admin-api-2.x/installation-for-odsapi-7x/admin-api-2x-iis-installation-powershell.md

update AdminAPI versions to 2.2.2

Update admin-api-2x-iis-installation-powershell.md, 
